export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard:view',
  USER_MANAGE: 'user:manage',
  USER_VIEW: 'user:view',
  SERVER_VIEW: 'server:view',
  SERVER_MANAGE: 'server:manage',
  ENVIRONMENT_VIEW: 'environment:view',
  ENVIRONMENT_MANAGE: 'environment:manage',
  APPLICATION_VIEW: 'application:view',
  APPLICATION_MANAGE: 'application:manage',
  CREDENTIAL_VIEW: 'credential:view',
  CREDENTIAL_MANAGE: 'credential:manage',
  DEPLOYMENT_VIEW: 'deployment:view',
  DEPLOYMENT_EXECUTE: 'deployment:execute',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS: PermissionKey[] = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS: Record<string, PermissionKey[]> = {
  Admin: ALL_PERMISSIONS,
  Developer: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.SERVER_VIEW,
    PERMISSIONS.ENVIRONMENT_VIEW,
    PERMISSIONS.APPLICATION_VIEW,
    PERMISSIONS.APPLICATION_MANAGE,
    PERMISSIONS.DEPLOYMENT_VIEW,
    PERMISSIONS.DEPLOYMENT_EXECUTE,
  ],
  QA: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.SERVER_VIEW,
    PERMISSIONS.ENVIRONMENT_VIEW,
    PERMISSIONS.APPLICATION_VIEW,
    PERMISSIONS.DEPLOYMENT_VIEW,
  ],
  UAT: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ENVIRONMENT_VIEW,
    PERMISSIONS.APPLICATION_VIEW,
    PERMISSIONS.DEPLOYMENT_VIEW,
  ],
  Viewer: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.SERVER_VIEW,
    PERMISSIONS.ENVIRONMENT_VIEW,
    PERMISSIONS.APPLICATION_VIEW,
    PERMISSIONS.DEPLOYMENT_VIEW,
  ],
};
